name: GitFlow Branch Protection

on:
  pull_request:
    branches: 
      - '**'  # Correcto para capturar cualquier branch

jobs:
  # Validación para feature/* a develop
  feature-to-develop:
    if: ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.base.ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR from feature/* to develop
        run: echo "Valid PR -> feature/* to develop."

  # Validación para develop a release/*
  develop-to-release:
    if: ${{ github.event.pull_request.head.ref == 'develop' && startsWith(github.event.pull_request.base.ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR from develop to release/*
        run: echo "Valid PR -> develop to release/*."

  # Validación para release/* a main
  release-to-main:
    if: ${{ startsWith(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR from release/* to main
        run: echo "Valid PR -> release/* to main."

  # Fallar si ninguna condición es válida
  invalid-pr:
    needs: [release-to-main, develop-to-release, feature-to-develop]
    runs-on: ubuntu-latest
    steps:
      - name: Check for invalid PR
        run: |
          echo "Invalid PR: This PR does not follow the GitFlow branch rules."
          exit 1